# Generated by Django 5.0.4 on 2024-05-28 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0002_product_total_sales_alter_order_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 1, 42, 16, 945069)),
        ),
    ]
