# Generated by Django 5.0.4 on 2024-05-29 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0003_alter_order_date_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_sales',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 11, 58, 490260)),
        ),
    ]
