# Generated by Django 5.0.4 on 2024-05-29 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0008_order_promo_code_alter_order_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 16, 45, 15, 353555)),
        ),
    ]
