# Generated by Django 5.0.4 on 2024-05-29 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autosalon', '0009_promo_discount_value_alter_order_date_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 0, 16, 48, 119792)),
        ),
    ]
